### ISSUE TITLE
getting error while executing $ pip install -r dev-requirements.txt

### ISSUE THREAD

**Issue by hariharry** [Netflix-Skunkworks/diffy#30]
The Error is 

`compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/harry/diffy/env/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-xihzs_85/python-levenshtein/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-0losak7n/install-record.txt --single-version-externally-managed --compile --install-headers /home/harry/diffy/env/include/site/python3.6/python-levenshtein" failed with error code 1 in /tmp/pip-install-xihzs_85/python-levenshtein/`

**Comment by hariharry** [comment]
Ubuntu 16.04 is my os 
I followed the exact commands from [diffy](http://diffy.readthedocs.io/en/latest/quickstart/index.html).
So can you give a step by step process of installing and doing this

**Comment by hariharry** [comment]
after installing so many packages(`sudo apt-get install build-essential autoconf libtool pkg-config python-opengl python-imaging python-pyrex python-pyside.qtopengl idle-python2.7 qt4-dev-tools qt4-designer libqtgui4 libqtcore4 libqt4-xml libqt4-test libqt4-script libqt4-network libqt4-dbus python-qt4 python-qt4-gl libgle3 python-dev libssl-dev`)   I sort out that error.

but is there any pre requisites before `diffy new baseline <asg>`  this command.
i have some questions about Pre-requisites(nothing mentioned in the docs)

1.Do the instance that installing diffy has to be in the auto scaling group?
2.How do i integrate aws account with the diffy (in the diffy folder so many python files are there in there so many times aws related detailes are mentioned (eg: in the plugins.py,auto-scaling.py etc) do i have to manually add it ?
please reply

**Comment by kevgliss** [comment]
We're missing a bit of documentation, so bear with us. 

If you're using Diffy's AWS plugins there are a few assumptions that Diffy makes.

- You have SSM enabled in your account and have the SSM agent on any instance you want to interrogate.
- Each instance that you would like to interrogate is in an AutoScalingGroup. 
- You have the proper IAM credentials to call both `DescribeAutoScalingGroups` and `SSMSendCommand` APIs.

They assumptions are based on the plugins we currently have within Diffy, that said if you wanted to target individual instances, or interrogate them a different way (e.g. SSH) you could but you would currently have to write you're own plugin to accomplish this. 

Writing you're own plugin is hopefully straightforward. See: http://diffy.readthedocs.io/en/latest/developer/plugins/index.html#plugin-interfaces

**Comment by forestmonster** [comment]
> - You have SSM enabled in your account and have the SSM agent on any instance you want to interrogate.

@hariharry, also note that when you're getting the SSM agent set up, you will need to [configure an access role for SSM](https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-configuring-access-role.html) to ensure that your agent can communicate with the AWS endpoint.

**Comment by forestmonster** [comment]
If after observing the recommendations above, you continue to have issues, please feel free to let us know.
