### ISSUE TITLE
Video for OSDFCon talk

### ISSUE THREAD

**Issue by ThorodanBrom** [Netflix-Skunkworks/diffy#44]
I really would like to understand how Diffy works, and noticed that you gave a talk at OSDFCon. I've checked out the slides, just wanted to know if a video will be released.

Thanks

**Comment by forestmonster** [comment]
Thanks @ThorodanBrom! I've asked the OSDFCon organizers if a video will be posted. I see that those slides don't have any of our speaker notes. [You can see speaker notes in this PDF version of the presentation](https://github.com/forestmonster/presentations/blob/master/diffy/diffy_querycon_sf_2018.pdf) released under GPL 3.0. If you're interested in a _demo_, we don't yet have a demo video posted but hope to post one soon.

**Comment by forestmonster** [comment]
Closing the loop on this... the conference organizers confirmed for me that they did not record any of the talks this year. sad face

**Comment by ThorodanBrom** [comment]
Thank you @forestmonster , for pointing me to the speaker notes, found them very helpful.
