### ISSUE TITLE
Add travis ci for building and testing Diffy PRs.

### ISSUE THREAD

**Issue by kevgliss** [Netflix-Skunkworks/diffy#6]

**Comment by kevgliss** [comment]
I believe we are blocked by https://github.com/spulec/moto/pull/1589 we could also pin back to an older version botocore.

**Comment by sr71-blackbird** [comment]
any update on this?

**Comment by forestmonster** [comment]
Forking moto to https://github.com/forestmonster/moto and will rely on that until the moto release.

**Comment by forestmonster** [comment]
Builds automatically now.
